.TH "inc/CommandHandler.hpp" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/CommandHandler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <string\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include <Stream\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBCommandHandler\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef bool(* \fBcmdhndlr_t\fP) (\fBCommandHandler\fP *, const char *, const char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBCommandHandler\&.hpp\fP Class for a more flexible command-like communication between two devices via serial
.PP
\fBAuthors\fP
.RS 4
albrdev (albrdev@gmail.com) 
.RE
.PP
\fBDate\fP
.RS 4
2020-03-02 
.RE
.PP

.SH "Typedef Documentation"
.PP 
.SS "typedef bool(* cmdhndlr_t) (\fBCommandHandler\fP *, const char *, const char *)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
