.TH "config_device.py" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_device.py
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBconfig_device\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBconfig_device\&.receiveResponse\fP (sp)"
.br
.ti -1c
.RI "def \fBconfig_device\&.sendCommand\fP (sp, cmd, *args)"
.br
.ti -1c
.RI "def \fBconfig_device\&.main\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBconfig_device\&.CMD_INIT\fP = '$$$'"
.br
.ti -1c
.RI "string \fBconfig_device\&.CMD_OK\fP = 'OK'"
.br
.ti -1c
.RI "string \fBconfig_device\&.CMD_FAIL\fP = 'FAIL'"
.br
.ti -1c
.RI "string \fBconfig_device\&.CMD_UNKNOWN\fP = 'UNKNOWN'"
.br
.ti -1c
.RI "string \fBconfig_device\&.CMD_ABORT\fP = 'ABORT'"
.br
.ti -1c
.RI "string \fBconfig_device\&.CMD_DT\fP = 'DT'"
.br
.ti -1c
.RI "\fBconfig_device\&.options\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.dest\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.type\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.str\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.help\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.metavar\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.int\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.required\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.False\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.default\fP"
.br
.ti -1c
.RI "\fBconfig_device\&.float\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
