.TH "config.h" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBAPPLY_CONFIG\fP"
.br
.ti -1c
.RI "#define \fBCONFIG_NSKEY\fP   { 0x23, 0xFD, 0xCF, 0x5D, 0x83, 0xFF, 0x5D, 0x15, 0xC5, 0x6A, 0x76, 0x8E, 0xC0, 0x77, 0xE4, 0x4D }"
.br
.ti -1c
.RI "#define \fBCONFIG_ASKEY\fP   { 0x33, 0xA0, 0x0A, 0x93, 0xAC, 0x6D, 0x81, 0xAF, 0xDE, 0xBE, 0xF5, 0x66, 0x0E, 0x90, 0xC0, 0xEF }"
.br
.ti -1c
.RI "#define \fBCONFIG_DEVADDR\fP   0x260115AF"
.br
.ti -1c
.RI "#define \fBCONFIG_NETID\fP   0x00000001"
.br
.ti -1c
.RI "#define \fBCONFIG_CHANNEL\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define APPLY_CONFIG"

.SS "#define CONFIG_ASKEY   { 0x33, 0xA0, 0x0A, 0x93, 0xAC, 0x6D, 0x81, 0xAF, 0xDE, 0xBE, 0xF5, 0x66, 0x0E, 0x90, 0xC0, 0xEF }"

.SS "#define CONFIG_CHANNEL   1"

.SS "#define CONFIG_DEVADDR   0x260115AF"

.SS "#define CONFIG_NETID   0x00000001"

.SS "#define CONFIG_NSKEY   { 0x23, 0xFD, 0xCF, 0x5D, 0x83, 0xFF, 0x5D, 0x15, 0xC5, 0x6A, 0x76, 0x8E, 0xC0, 0x77, 0xE4, 0x4D }"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
