.TH "config_device" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_device
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBreceiveResponse\fP (sp)"
.br
.ti -1c
.RI "def \fBsendCommand\fP (sp, cmd, *args)"
.br
.ti -1c
.RI "def \fBmain\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBCMD_INIT\fP = '$$$'"
.br
.ti -1c
.RI "string \fBCMD_OK\fP = 'OK'"
.br
.ti -1c
.RI "string \fBCMD_FAIL\fP = 'FAIL'"
.br
.ti -1c
.RI "string \fBCMD_UNKNOWN\fP = 'UNKNOWN'"
.br
.ti -1c
.RI "string \fBCMD_ABORT\fP = 'ABORT'"
.br
.ti -1c
.RI "string \fBCMD_DT\fP = 'DT'"
.br
.ti -1c
.RI "\fBoptions\fP"
.br
.ti -1c
.RI "\fBdest\fP"
.br
.ti -1c
.RI "\fBtype\fP"
.br
.ti -1c
.RI "\fBstr\fP"
.br
.ti -1c
.RI "\fBhelp\fP"
.br
.ti -1c
.RI "\fBmetavar\fP"
.br
.ti -1c
.RI "\fBint\fP"
.br
.ti -1c
.RI "\fBrequired\fP"
.br
.ti -1c
.RI "\fBFalse\fP"
.br
.ti -1c
.RI "\fBdefault\fP"
.br
.ti -1c
.RI "\fBfloat\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def config_device\&.main ()"

.SS "def config_device\&.receiveResponse ( sp)"

.SS "def config_device\&.sendCommand ( sp,  cmd, * args)"

.SH "Variable Documentation"
.PP 
.SS "string config_device\&.CMD_ABORT = 'ABORT'"

.SS "string config_device\&.CMD_DT = 'DT'"

.SS "string config_device\&.CMD_FAIL = 'FAIL'"

.SS "string config_device\&.CMD_INIT = '$$$'"

.SS "string config_device\&.CMD_OK = 'OK'"

.SS "string config_device\&.CMD_UNKNOWN = 'UNKNOWN'"

.SS "config_device\&.default"

.SS "config_device\&.dest"

.SS "config_device\&.False"

.SS "config_device\&.float"

.SS "config_device\&.help"

.SS "config_device\&.int"

.SS "config_device\&.metavar"

.SS "config_device\&.options"
\fBInitial value:\fP
.PP
.nf
1 =  argparse\&.ArgumentParser(
2         description="",
3         epilog=""
4     )
.fi
.SS "config_device\&.required"

.SS "config_device\&.str"

.SS "config_device\&.type"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
