.TH "inc/debug.hpp" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/debug.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNOP\fP   ((void)0)"
.br
.ti -1c
.RI "#define \fBDebugPrint\fP(\&.\&.\&.)   \fBNOP\fP"
.br
.ti -1c
.RI "#define \fBDebugPrintLine\fP(\&.\&.\&.)   \fBNOP\fP"
.br
.ti -1c
.RI "#define \fBDebugWrite\fP(\&.\&.\&.)   \fBNOP\fP"
.br
.ti -1c
.RI "#define \fBDebugFlush\fP()   \fBNOP\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DebugFlush()   \fBNOP\fP"

.SS "#define DebugPrint( \&.\&.\&.)   \fBNOP\fP"

.SS "#define DebugPrintLine( \&.\&.\&.)   \fBNOP\fP"

.SS "#define DebugWrite( \&.\&.\&.)   \fBNOP\fP"

.SS "#define NOP   ((void)0)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
