.TH "back-end/get_data.cpp" 3 "Tue Mar 10 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
back-end/get_data.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <curl/curl\&.h>\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBurl\fP   'https://albrdev\-test\-01\&.data\&.thethingsnetwork\&.org/api/v2/query?last=1d'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static size_t \fBwrite_data\fP (void *ptr, size_t size, size_t nmemb, void *stream)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define url   'https://albrdev\-test\-01\&.data\&.thethingsnetwork\&.org/api/v2/query?last=1d'"

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SS "static size_t write_data (void * ptr, size_t size, size_t nmemb, void * stream)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
