.TH "src/LightTracker.cpp" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/LightTracker.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'LightTracker\&.hpp'\fP
.br
\fC#include <Arduino\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSERVO_ANGLE_MIN\fP   0"
.br
.ti -1c
.RI "#define \fBSERVO_ANGLE_MAX\fP   180"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define SERVO_ANGLE_MAX   180"

.SS "#define SERVO_ANGLE_MIN   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
