.TH "LightTracker" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LightTracker
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LightTracker\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "int \fBGetHorizontalPosition\fP (void)"
.br
.ti -1c
.RI "int \fBGetVerticalPosition\fP (void)"
.br
.ti -1c
.RI "bool \fBPoll\fP (void)"
.br
.ti -1c
.RI "void \fBBegin\fP (void)"
.br
.ti -1c
.RI "\fBLightTracker\fP (uint8_t servoHPin, uint8_t servoVPin, uint8_t prULPin, uint8_t prURPin, uint8_t prDLPin, uint8_t prDRPin, int activeLightLevel=250, int tolerance=50, int angleHMargin=15, int angleVMargin=15)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LightTracker::LightTracker (uint8_t servoHPin, uint8_t servoVPin, uint8_t prULPin, uint8_t prURPin, uint8_t prDLPin, uint8_t prDRPin, int activeLightLevel = \fC250\fP, int tolerance = \fC50\fP, int angleHMargin = \fC15\fP, int angleVMargin = \fC15\fP)"

.SH "Member Function Documentation"
.PP 
.SS "void LightTracker::Begin (void)"

.SS "int LightTracker::GetHorizontalPosition (void)"

.SS "int LightTracker::GetVerticalPosition (void)"

.SS "bool LightTracker::Poll (void)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
