.TH "md_back-end__r_e_a_d_m_e" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_back-end__r_e_a_d_m_e \- Back-end 
The back-end needed to store the data for further use over time that the module sent over LoRaWAN\&.
.br
This is needed since the data stored on The Things Network isn't stored longer then 7 days 
.br
 if an extra application is included named Storage data\&. 
.br

