.TH "md_documentation" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_documentation \- Documentation 

.SH "Github Repository:"
.PP
The repository of the main controller
.br
https://github.com/projectRise 
.br

.br
The repository of the local back-end
.br
https://github.com/projectRise/back-end 
.br

.br
The repository of the front-end
.br
https://github.com/projectRise/front-end 
.br

.br
 
.SH "Jira:"
.PP
The jira page of the project
.br
https://projektrise.atlassian.net 
.br

.br
 
.SH "Project Dokumentation:"
.PP
Project speficifation\&. 
.br
https://docs.google.com/document/d/1qDZcl1V8Ov-OLbcYm44G_peAaIZKt5wkov6uv6Ui07Q/edit?usp=sharing 
.br

.br
Pin layout of project\&. 
.br
https://docs.google.com/spreadsheets/d/16jWboL5m84bEegnQy6BUv7_CsHupfp_3EN4pvGDylac/edit?usp=sharing 
.br

