.TH "inc/misc.hpp" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/misc.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'CommandHandler\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBCMD_INIT\fP   '$$$'"
.br
.ti -1c
.RI "#define \fBCMD_OK\fP   'OK'"
.br
.ti -1c
.RI "#define \fBCMD_FAIL\fP   'FAIL'"
.br
.ti -1c
.RI "#define \fBCMD_UNKNOWN\fP   'UNKNOWN'"
.br
.ti -1c
.RI "#define \fBCMD_ABORT\fP   'ABORT'"
.br
.ti -1c
.RI "#define \fBCMD_SD\fP   'SD'"
.br
.ti -1c
.RI "#define \fBCMD_DT\fP   'DT'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBhandleCommand\fP (\fBCommandHandler\fP *self, const char *cmd, const char *args)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define CMD_ABORT   'ABORT'"

.SS "#define CMD_DT   'DT'"

.SS "#define CMD_FAIL   'FAIL'"

.SS "#define CMD_INIT   '$$$'"

.SS "#define CMD_OK   'OK'"

.SS "#define CMD_SD   'SD'"

.SS "#define CMD_UNKNOWN   'UNKNOWN'"

.SH "Function Documentation"
.PP 
.SS "bool handleCommand (\fBCommandHandler\fP * self, const char * cmd, const char * args)"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
