.TH "src/misc.cpp" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/misc.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'misc\&.hpp'\fP
.br
\fC#include <errno\&.h>\fP
.br
\fC#include <RTClib\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBhandleCommand\fP (\fBCommandHandler\fP *self, const char *cmd, const char *args)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "unsigned long \fBsleepDuration\fP"
.br
.ti -1c
.RI "RTC_DS3231 \fBrtc\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool handleCommand (\fBCommandHandler\fP * self, const char * cmd, const char * args)"

.SH "Variable Documentation"
.PP 
.SS "RTC_DS3231 rtc"

.SS "unsigned long sleepDuration"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
