.TH "inc/types.h" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/types.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef float \fBsingle_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBheader_t\fP"
.br
.ti -1c
.RI "\fBsensordata_t\fP"
.br
.ti -1c
.RI "\fBsensordata2_t\fP"
.br
.ti -1c
.RI "\fBcollection_t\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef float \fBsingle_t\fP"

.SH "Function Documentation"
.PP 
.SS "struct __attribute__ ((packed))"

.SH "Variable Documentation"
.PP 
.SS "collection_t"

.SS "header_t"

.SS "sensordata2_t"

.SS "sensordata_t"

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
