.TH "inc/WeatherShield.hpp" 3 "Thu May 14 2020" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
inc/WeatherShield.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <Wire\&.h>\fP
.br
\fC#include 'SparkFunMPL3115A2\&.h'\fP
.br
\fC#include 'SparkFun_Si7021_Breakout_Library\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBWeatherShield\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBWeatherShield\&.hpp\fP Wrapper class for SparkFun's weather shield
.PP
\fBAuthors\fP
.RS 4
albrdev (albrdev@gmail.com) 
.RE
.PP
\fBDate\fP
.RS 4
2020-03-02 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
